### PR TITLE
 Fixing bugs in synthesize time 

### PR DESCRIPTION
**Pull request by Yeongtae**
- Being able to load the wavenet checkpoint
- Replacing missing Information about speaker id, time and index

### CODE REVIEW

**Comment by Yeongtae** [comment]
Finish all possible tests

**Comment by Rayhane-mamah** [comment]
I am assuming you made changed to the shadow_saver because it was failing to load the model for you? Could you describe the exact steps you followed to get to that loading failure bug? I cannot reproduce with default shadow_saver no matter how hard I try. thanks :)

**Comment by Yeongtae** [comment]
Did you need a docker that i use?

**Comment by Yeongtae** [comment]
I have made a wavenet checkpoint using your latest commit. 
When i run synthesis.py, it is not possible to load the wavenet checkpoint. Bacause it trying to load tensors with wrong variable names.

**Comment by Yeongtae** [comment]
Many peoples have taken same isue like #98

**Comment by Rayhane-mamah** [comment]
Yeah I saw that many people have the same issue and I can't quite figure out how you guys are getting this issue while I trained my repo on 4 different machines, with dockers and without and never actually got that bug.. I am currently making few changes here and there for synthesis pipeline (to make it batch wise, and I'm aware I left things missing.) so I will have to pick what works best with the repo dev plan and drop what's inconsistent with it. I guess I'll add your checkpoint loading method as an alternative for people with bugs. Thanks for the contribution @Yeongtae  ;)

**Comment by Rayhane-mamah** [comment]
By the way, that "model_1" thing is probably happening because you already have another tf graph constructed with name "model" before building the Wavenet model for synthesis. Are you by any chance trying to synthesize while the model is training in the background?

**Comment by Yeongtae** [comment]
I guess tacotron use 'model' in synthesis time.

**Comment by Rayhane-mamah** [comment]
Oh synthesis with the entire T2 pipeline, I'll run few tests on that, there's an easy fix for wavenet checkpoints in that case. I'll come back to you on that

**Comment by Rayhane-mamah** [comment]
We have added the missing features in Wavenet synthesis, fixed T2 synthesis by removing Tacotron graph once it's done predicting. We also made synthesis of Wavenet and Tacotron (GTA) batch wise to accelerate synthesis process on multiple sentences synthesis and to make maximal use of GPU computation power. Thanks for your efforts!

**Pull request closed without merging**
