### PR TITLE
Fix Issue#67 and Issue#64

### PR DESCRIPTION
**Pull request by gaob13**

### CODE REVIEW

**Comment by gaob13** [comment]
and Issue #82 .

**Comment by gaob13** [comment]
Dear @cuicp ,
If the models are trained BEFORE this modification, the trained models cannot be loaded this way.
Please train the model again after fixing your code.

**Comment by atreyas313** [comment]
Hi @cuicp,
I have also encountered a problem when synthesizing wavenet in (https://github.com/Rayhane-mamah/Tacotron-2), could you fix it?

**Comment by Rayhane-mamah** [comment]
This was fixed in latest commits, however thanks for your contributions

**Pull request closed without merging**
